/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

http://projecteuler.net/problem=2
*/

#include <stdio.h>

int main()
{
	long long int a = 1;
	long long int b = 1;
	long long int c = 0;
	long long int sum = 0;
	while(1) {
		c = a + b;
		if(c > 4000000)
			break;
		a = b;
		b = c;
		if(!(c & 1))
			sum = sum + c;
	}
	printf("sum is: %lld\n", sum);
	return 0;
}
